# HackHaste keyboard layout. Dr. Marcus Roe, https://drm.cc/ . MIT License.
# S60 emulator epoc.ini KeyMap lines (physical QWERTY to HackHaste).

KeyMap ` `
KeyMap 1 1
KeyMap 2 2
KeyMap 3 3
KeyMap 4 4
KeyMap 5 5
KeyMap 6 6
KeyMap 7 [
KeyMap 8 ]
KeyMap 9 v
KeyMap 0 x
KeyMap - z
KeyMap = q
KeyMap q 7
KeyMap w 8
KeyMap e 9
KeyMap r 0
KeyMap t -
KeyMap y k
KeyMap u l
KeyMap i c
KeyMap o g
KeyMap p y
KeyMap [ w
KeyMap ] ;
KeyMap \ \
KeyMap a u
KeyMap s i
KeyMap d a
KeyMap f e
KeyMap g o
KeyMap h h
KeyMap j r
KeyMap k s
KeyMap l t
KeyMap ; n
KeyMap ' p
KeyMap z '
KeyMap x ,
KeyMap c .
KeyMap v /
KeyMap b =
KeyMap n j
KeyMap m m
KeyMap , d
KeyMap . b
KeyMap / f
